title: BENY
email: beynrodsoto@gamil.com
greeting: EL BLOG DE BENY
description: > # this means to ignore newlines until another tag
    Israh is a responsive Jekyll theme with warm greys, a single column layout, and not much else.
favicon: favicon.png
navlinks:
    -
        text: inicio
        url: /
        internal: True
    -
        text: Instagram
        url: https://www.instagram.com/beny_rodsot/
        internal: False
    

# Build settings
paginate: 3
#baseurl: "/israh-jekyll-theme" # the subpath of your site, e.g. /blog/
#baseurl: ""
url: "https://ezrasavard.github.io" # the base hostname & protocol for your site
highlights: pygments
permalink: posts/:title/
include: ["_pages"]
plugins: [jekyll-paginate]
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
    sass_dir: _sass
    style: compressed
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: "Ezra Savard"
            layout: "post"
    -
        scope:
            path: ""
            type: "pages"
        values:
            author: "Ezra Savard"
            layout: "page"

